version: '3.8'
services:
  database:
    image: mysql:8
    command: mysqld --authentication_policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name: auth-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: local-auth
  app:
    build: .
    container_name: auth-api
    ports:
      - 3333:3333
      - 9230:9229
    volumes:
      - .:/usr/src/auth-api
    links:
      - database
    depends_on:
      - database
    command: sh -c "/wait; npm ci; npx prisma migrate deploy; npm run start:dev"
    environment:
      - WAIT_HOSTS=database:3306
      - WAIT_TIMEOUT=1000
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=15
